### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by amakvana** [LexouilleTM/yuzu-mods-archive#1]
Hi Lex! 

Hope you're well! I'm the dev of SwitchEmuModDownloader (SEMD).

I was wondering, with your permission of course, if it's possible I could also use this repository as an additional mirror to download Switch-Mods for Yuzu? As the official repo has now been taken offline and you've uploaded a full dump of the Switch-Mods wiki.

Full credit and acknowledgements would be added within my repo, linking you and here.

You'd be able to opt-out whenever you like but you'd have to give me a bit of time to push an update to do this. I do know that having your repo available would benefit all users of SEMD massively and increase exposure to your repo too.

Let me know what you think.

Cheers!

**Comment by LexouilleTM** [comment]
Hi!

It is with great pleasure that you can use this. Thank you for asking permission before doing this and good luck 🙏

**Comment by LexouilleTM** [comment]
(And I apologize for my bad English, it's not my main language)

**Comment by amakvana** [comment]
Thank you very much! Thoroughly appreciated
